### ISSUE TITLE
parser does not decode query string  before validating

### ISSUE THREAD

**Issue by numerical25** [ethanresnick/json-api-custom-query#4]
JSON API Custom Query does not decode urls before it evaluates them. Some API Testing Applicattions such as Postman encode the url's before sending them out. Is it possible to have a fix for  this ?

When using applications such as Postman, urls turn from this...

`filter=(:or,(:and,(events.end_date,:gte,1549745450224),(events.start_date,:lte,1549745450224)))`

into this...

`filter=%28:or,%28:and,%28events.end_date,:gte,1549745450224%29,%28events.start_date,:lte,1549745450224%29%29%29`

The parser trys to validate the url without making an attempt to decode the url and throws an error. A simple decode before evaluating the url should fix this issue. 

Please see issue   #5 for a proposed change.

**Comment by ethanresnick** [comment]
See my response on the main json-api repo. But basically, we can't blindly decode the whole string as that will create a lot of broken parses.
