### ISSUE TITLE
proposal: omit square brackets

### ISSUE THREAD

**Issue by yurks** [ethanresnick/json-api-custom-query#7]
just for simplify: 

``(field,:op,[`val1`,`val2`,field2])`` === ``(field,:op,`val1`,`val2`,field2)``

**Comment by ethanresnick** [comment]
I mean, operators [i.e., the code that uses the parse result from this library] are totally allowed to treat all of their trailing arguments as a single list (like rest parameters in JS). But that doesn't mean that the syntax can remove the list form (with square brackets entirely). For example, what if you want to have two lists as adjacent arguments, like `(:eq,[1,2,3],[1,2,3])`. This obviously doesn't work without the square brackets.

**Comment by yurks** [comment]
The reason of this proposal is aesthetic too)
Form like ``(field,:op,`val1`,`val2`,field2)`` could be interpret as ``(field,:op,[`val1`,`val2`,field2])`` for binary operstors, but gives a bit more flexibility when using this filtering for building requests to "non-classic DBs" with custom operators.
For example, ``(city,:prefix,`New`,`Los`)`` looks bit better then ``(city,:prefix,[`New`,`Los`])``.
